token:
name: "Foundation"
activity: "Nothing here"
mainGuild: "000000000000000000"
debug: []
mySQL_enabled: false
mySQL_host: "Foundation"
myQL_port: 3306
mySQL_databas: "Foundation"
mySQL_username: "Foundation_User"
mySQL_password: "Foundation_Password"
mySQL_storeMembers: true