# !-----------------------------------------------------------------------------------------------!
#              Welcome to the main configuration of the foundation system
#
#           This file contains all the main settings of the discord bot in here
# !-----------------------------------------------------------------------------------------------!
# **NOTE: This file is here to show the default methods that need to be inside the bot at all times!**
# -------------------------------------------------------------------------------------------------
#  The essential setting for the bot.
#  **IMPORTANT** these settings need to be configured!
# -------------------------------------------------------------------------------------------------
Bot:
  
  # The token for the bot
  # A token can be made inside the discors applications portal
  # https://discord.com/developers/applications
  Token: "0000000000000000000000000000000000000000"
  
  # The main guild of the bot
  MainGuild: "000000000000000000"
  
  # The name of your bot
  Name: "DiscordBot"

# -------------------------------------------------------------------------------------------------
#  Manage the activity of the bot
#  !!This system is still in BETA!!
# -------------------------------------------------------------------------------------------------
Activity:

  # **IMPORTANT** THIS FEATURE IS NOT WORKING AT THIS MOMENT
  # The type of the activity
  # Possible options: PLAYING, STREAMING, LISTENING and WATCHING
  Type: "WATCHING"

  # The message after the activity type
  Message: "Foundation"

Developer:
  # The name of the developer of the bot
  Name: "Greazi"
  # The website of the developer of the bot
  Website: "https://greazi.com"
  # The image of the developer of the bot
  Image: "https://www.greazi.com/wp-content/uploads/2021/08/cropped-bannerempty.png"

Embed:
  Link: "https://greazi.com"
  Footer: "Copyright ©Greazi"
  Image:
    Author: "https://www.greazi.com/wp-content/uploads/2021/08/cropped-bannerempty.png"
    Footer: "https://www.greazi.com/wp-content/uploads/2021/08/cropped-bannerempty.png"

Commands:
  Stop:
    Enabled: true
    AllowedRoles:
      - owner

# -------------------------------------------------------------------------------------------------
#  Manage the console of the bot
# -------------------------------------------------------------------------------------------------
Console:
  Commands:
    # Should console commands be enabled?
    Enabled: true

    # Commands that are disabled
    Disabled: []

# -------------------------------------------------------------------------------------------------
# Configure the database settings here
# -------------------------------------------------------------------------------------------------
Database:

  # Should we store all the data on the database
  Enabled: false
  
  # The database information
  Host: "localhost"
  Port: 3306
  Databas: "Foundation"
  Username: "Foundation_User"
  Password: "Foundation_Password"

# -------------------------------------------------------------------------------------------------
# List of section names that will print informative messages about their features.
# If you have issues, try enabling either of these sections to self-diagnose:
# [Startup, Database, SlashCommandHandler]
# -------------------------------------------------------------------------------------------------
Debug: []
